### ISSUE TITLE
Thank you for providing feedback HW1

### ISSUE THREAD

**Issue by kunchieh** [kunchieh/stat679work#6]
@WangTJ

@rebeccapost

@cecileane 

Please take a look of my HW1 and providing some feedbacks. Thank you.

**Comment by cecileane** [comment]
Hi Jason,
Did you open a new issue because you made some changes and have an update? If not, it's redundant with #5 and you can close this issue, to keep all the discussion in the same place in #5.

**Comment by cecileane** [comment]
Oh I guess you turned your repository public for the time being, that's the change. Thanks Jason!
